//初始化订单基本信息导出字段
var index = 0;
saveObject('order_baseInfo_exportFields', {
    "id": "order_baseInfo_exportFields", "values": [
        {"id": "id", "isChecked": "true", "name": "订单ID", "columnWidth": "20",index:index++},
        {"id": "orderAliasCode", "isChecked": "true", "name": "订单号", "columnWidth": "22",index:index++},
        {"id": "orderType", "isChecked": "true", "name": "订单类型", "columnWidth": "12",index:index++},
        {"id": "orderMerchant", "isChecked": "true", "name": "订单所属商家", "columnWidth": "16",index:index++},
        {"id": "createTime", "isChecked": "true", "name": "订单生成时间", "columnWidth": "20",index:index++},
        {"id": "createDate", "isChecked": "false", "name": "生成订单日期", "columnWidth": "20",index:index++},
        {"id": "receiveName", "isChecked": "true", "name": "收货人姓名", "columnWidth": "12",index:index++},
        {"id": "receiveTel", "isChecked": "true", "name": "收货人电话", "columnWidth": "20",index:index++},
        {"id": "receiveAddress", "isChecked": "true", "name": "收货人地址", "columnWidth": "20",index:index++},
        {"id": "certificate", "isChecked": "false", "name": "身份证号码", "columnWidth": "25", index: index++},
        {"id": "idCardFrontPic", "isChecked": "false", "name": "身份证正面照", "columnWidth": "25", index: index++},
        {"id": "idCardBackPic", "isChecked": "false", "name": "身份证反面照", "columnWidth": "25", index: index++},
        {"id": "deliveryArea", "isChecked": "true", "name": "配送地区", "columnWidth": "25",index:index++},
        {"id": "deliveryWay", "isChecked": "true", "name": "配送方式", "columnWidth": "10",index:index++},
        {"id": "deliveryTime", "isChecked": "false", "name": "配送时间", "columnWidth": "10",index:index++},
        {"id": "receiveMobile", "isChecked": "false", "name": "收货人手机", "columnWidth": "15",index:index++},
        {"id": "isDeliveryPoint", "isChecked": "true", "name": "是否自提", "columnWidth": "10",index:index++},
        {"id": "deliveryPointName", "isChecked": "true", "name": "自提点名称", "columnWidth": "12",index:index++},
        {"id": "buyerUserId", "isChecked": "true", "name": "会员ID", "columnWidth": "12",index:index++},
        {"id": "buyerLoginId", "isChecked": "true", "name": "会员登陆号", "columnWidth": "12",index:index++},
        {"id": "buyerRealName", "isChecked": "true", "name": "会员真实姓名", "columnWidth": "16",index:index++},
        {"id": "groups", "isChecked": "true", "name": "会员等级", "columnWidth": "20",index:index++},
        {"id": "promotionUserId", "isChecked": "true", "name": "推荐人内部ID", "columnWidth": "16",index:index++},
        {"id": "promotionLoginId", "isChecked": "true", "name": "推荐人登录帐号", "columnWidth": "22",index:index++},
        {"id": "promotionRealName", "isChecked": "true", "name": "推荐人真实姓名", "columnWidth": "16",index:index++},
        {"id": "logisticsName", "isChecked": "true", "name": "物流商", "columnWidth": "12",index:index++},
        {"id": "billNo", "isChecked": "false", "name": "物流运单号", "columnWidth": "12",index:index++},
        {"id": "orderTotalPrice", "isChecked": "true", "name": "订单总金额", "columnWidth": "12",index:index++},
        {"id": "deliveryFee", "isChecked": "true", "name": "订单运费", "columnWidth": "12",index:index++},
        {"id": "categorySufRebatePreferPrice", "isChecked": "true", "name": "订单优惠金额", "columnWidth": "16",index:index++},
        {"id": "deliveryProductPreferPrice", "isChecked": "true", "name": "运费优惠金额", "columnWidth": "16",index:index++},
        {"id": "payInfo", "isChecked": "true", "name": "订单支付方式", "columnWidth": "30",index:index++},
        {"id": "couponPay", "isChecked": "true", "name": "购物券支付", "columnWidth": "30",index:index++},
        {"id": "processState", "isChecked": "true", "name": "订单处理状态", "columnWidth": "16",index:index++},
        {"id": "payState", "isChecked": "true", "name": "订单支付状态", "columnWidth": "16",index:index++},
        {"id": "finishTime", "isChecked": "true", "name": "订单完成时间", "columnWidth": "20",index:index++},
        {"id": "finishDate", "isChecked": "true", "name": "订单完成日期", "columnWidth": "16",index:index++},
        {"id": "invoiceInfo", "isChecked": "true", "name": "发票信息", "columnWidth": "30",index:index++},
        {"id": "desc", "isChecked": "true", "name": "订单备注", "columnWidth": "20",index:index++},
        {"id": "customerMessage", "isChecked": "true", "name": "客户留言", "columnWidth": "20",index:index++},
        {"id": "createIP", "isChecked": "true", "name": "创建者IP", "columnWidth": "16",index:index++},
        {"id": "orderSource", "isChecked": "true", "name": "订单来源", "columnWidth": "16",index:index++},
        {"id": "confirmTime", "isChecked": "true", "name": "订单确认时间", "columnWidth": "20",index:index++},
        {"id": "payTime", "isChecked": "true", "name": "订单支付时间", "columnWidth": "20",index:index++},
        {"id": "shippedTime", "isChecked": "true", "name": "订单出库时间", "columnWidth": "20",index:index++},
        {"id": "cancelTime", "isChecked": "true", "name": "订单取消时间", "columnWidth": "20",index:index++},
        {"id": "lastModifyTime", "isChecked": "true", "name": "最后修改时间", "columnWidth": "20",index:index++},
        {"id": "payRecs", "isChecked": "false", "name": "订单支付信息", "columnWidth": "20",index:index++}
    ]
});
index = 0;
//初始化订单item信息导出字段
saveObject('order_item_exportFields', {
    "id": "order_item_exportFields", "values": [
        {"id": "id", "isChecked": "true", "name": "订单ID", "columnWidth": "20",index:index++},
        {"id": "orderAliasCode", "isChecked": "true", "name": "订单号", "columnWidth": "22",index:index++},
        {"id": "createTime", "isChecked": "false", "name": "订单生成时间", "columnWidth": "20",index:index++},
        {"id": "createDate", "isChecked": "true", "name": "生成订单日期", "columnWidth": "20",index:index++},
        {"id": "orderType", "isChecked": "true", "name": "订单类型", "columnWidth": "12",index:index++},
        {"id": "orderMerchant", "isChecked": "true", "name": "订单所属商家", "columnWidth": "16",index:index++},
        {"id": "orderSource", "isChecked": "true", "name": "订单来源", "columnWidth": "16",index:index++},
        {"id": "productId", "isChecked": "true", "name": "商品ID", "columnWidth": "12",index:index++},
        {"id": "realSkuId", "isChecked": "true", "name": "商品编码", "columnWidth": "16",index:index++},
        {"id": "baseRealSkuId", "isChecked": "false", "name": "基准SKU编码", "columnWidth": "20",index:index++},
        {"id": "baseSkuAmount", "isChecked": "true", "name": "基准SKU数量", "columnWidth": "20",index:index++},
        {"id": "productName", "isChecked": "true", "name": "商品名称", "columnWidth": "20",index:index++},
        {"id": "column", "isChecked": "true", "name": "商品分类", "columnWidth": "30",index:index++},
        {"id": "amount", "isChecked": "true", "name": "数量", "columnWidth": "8",index:index++},
        {"id": "unit", "isChecked": "true", "name": "单位", "columnWidth": "8",index:index++},
        {"id": "buyerUserId", "isChecked": "true", "name": "会员ID", "columnWidth": "12",index:index++},
        {"id": "buyerRealName", "isChecked": "true", "name": "会员真实姓名", "columnWidth": "16",index:index++},
        {"id": "groups", "isChecked": "true", "name": "会员等级", "columnWidth": "20",index:index++},
        {"id": "originalUnitPrice", "isChecked": "true", "name": "商品原价", "columnWidth": "12",index:index++},
        {"id": "unitPrice", "isChecked": "true", "name": "商品单价", "columnWidth": "12",index:index++},
        {"id": "supplyPrice", "isChecked": "true", "name": "供货价", "columnWidth": "12",index:index++},
        {"id": "totalPrice", "isChecked": "true", "name": "商品总价", "columnWidth": "12",index:index++},
        {"id": "erpPrice", "isChecked": "true", "name": "ERP原价", "columnWidth": "12",index:index++},
        {"id": "isPresent", "isChecked": "true", "name": "是否赠品", "columnWidth": "10",index:index++},
        {"id": "promotionId", "isChecked": "true", "name": "促销规则ID", "columnWidth": "20",index:index++},
        {"id": "promotionName", "isChecked": "true", "name": "促销规则名称", "columnWidth": "20",index:index++},
        {"id": "erpPromotionId", "isChecked": "true", "name": "线下促销规则ID", "columnWidth": "20",index:index++},
        {"id": "processState", "isChecked": "true", "name": "处理状态", "columnWidth": "10",index:index++},
        {"id": "payState", "isChecked": "true", "name": "支付状态", "columnWidth": "10",index:index++},
        {"id": "productSpec", "isChecked": "true", "name": "商品规格", "columnWidth": "16",index:index++},
        {"id": "receiveName", "isChecked": "true", "name": "收货人姓名", "columnWidth": "12",index:index++},
        {"id": "receiveMobile", "isChecked": "true", "name": "收货人手机", "columnWidth": "16",index:index++},
        {"id": "receiveAddress", "isChecked": "true", "name": "收货人地址", "columnWidth": "30",index:index++},
        {"id": "deliveryArea", "isChecked": "true", "name": "配送地区", "columnWidth": "25",index:index++},
        {"id": "deliveryWay", "isChecked": "true", "name": "配送方式", "columnWidth": "12",index:index++},
        {"id": "deliveryTime", "isChecked": "false", "name": "配送时间", "columnWidth": "20",index:index++},
        {"id": "receiveMobile", "isChecked": "false", "name": "收货人手机", "columnWidth": "15",index:index++},
        {"id": "isDeliveryPoint", "isChecked": "true", "name": "是否自提", "columnWidth": "10",index:index++},
        {"id": "deliveryPointName", "isChecked": "true", "name": "自提点名称", "columnWidth": "20",index:index++}
    ]
});
index = 0;
//初始化订单信息导出字段
saveObject('order_all_exportFields', {
    "id": "order_all_exportFields", "values": [
        {"id": "id", "isChecked": "true", "name": "订单ID", "columnWidth": "20",index:index++},
        {"id": "orderAliasCode", "isChecked": "true", "name": "订单号", "columnWidth": "22",index:index++},
        {"id": "orderType", "isChecked": "true", "name": "订单类型", "columnWidth": "12",index:index++},
        {"id": "orderMerchant", "isChecked": "true", "name": "订单所属商家", "columnWidth": "16",index:index++},
        {"id": "orderSource", "isChecked": "true", "name": "订单来源", "columnWidth": "16",index:index++},
        {"id": "createTime", "isChecked": "true", "name": "订单生成时间", "columnWidth": "20",index:index++},
        {"id": "createDate", "isChecked": "true", "name": "订单生成日期", "columnWidth": "20",index:index++},
        {"id": "receiveName", "isChecked": "true", "name": "收货人姓名", "columnWidth": "12",index:index++},
        {"id": "receiveTel", "isChecked": "true", "name": "收货人电话", "columnWidth": "20",index:index++},
        {"id": "receiveAddress", "isChecked": "true", "name": "收货人地址", "columnWidth": "20",index:index++},
        {"id": "certificate", "isChecked": "true", "name": "身份证号码", "columnWidth": "25", index: index++},
        {"id": "idCardFrontPic", "isChecked": "false", "name": "身份证正面照", "columnWidth": "25", index: index++},
        {"id": "idCardBackPic", "isChecked": "false", "name": "身份证反面照", "columnWidth": "25", index: index++},
        {"id": "deliveryArea", "isChecked": "true", "name": "配送地区", "columnWidth": "25",index:index++},
        {"id": "deliveryWay", "isChecked": "true", "name": "配送方式", "columnWidth": "10",index:index++},
        {"id": "deliveryTime", "isChecked": "false", "name": "配送时间", "columnWidth": "10",index:index++},
        {"id": "receiveMobile", "isChecked": "false", "name": "收货人手机", "columnWidth": "15",index:index++},
        {"id": "isDeliveryPoint", "isChecked": "true", "name": "是否自提", "columnWidth": "10",index:index++},
        {"id": "deliveryPointName", "isChecked": "true", "name": "自提点名称", "columnWidth": "12",index:index++},
        {"id": "buyerUserId", "isChecked": "true", "name": "会员ID", "columnWidth": "12",index:index++},
        {"id": "buyerLoginId", "isChecked": "true", "name": "会员登陆号", "columnWidth": "12",index:index++},
        {"id": "buyerRealName", "isChecked": "true", "name": "会员真实姓名", "columnWidth": "16",index:index++},
        {"id": "groups", "isChecked": "true", "name": "会员等级", "columnWidth": "20",index:index++},
        {"id": "orderTotalPrice", "isChecked": "true", "name": "订单总金额", "columnWidth": "12",index:index++},
        {"id": "logisticsName", "isChecked": "true", "name": "物流商", "columnWidth": "12",index:index++},
        {"id": "billNo", "isChecked": "true", "name": "物流运单号", "columnWidth": "12",index:index++},
        {"id": "deliveryFee", "isChecked": "true", "name": "订单运费", "columnWidth": "12",index:index++},
        {"id": "deliveryProductPreferPrice", "isChecked": "true", "name": "运费优惠金额", "columnWidth": "16",index:index++},
        {"id": "payInfo", "isChecked": "true", "name": "订单支付方式", "columnWidth": "30",index:index++},
        {"id": "couponPay", "isChecked": "true", "name": "购物券支付", "columnWidth": "30",index:index++},
        {"id": "processState", "isChecked": "true", "name": "订单处理状态", "columnWidth": "16",index:index++},
        {"id": "payState", "isChecked": "true", "name": "订单支付状态", "columnWidth": "16",index:index++},
        {"id": "finishTime", "isChecked": "true", "name": "订单完成时间", "columnWidth": "20",index:index++},
        {"id": "finishDate", "isChecked": "true", "name": "订单完成日期", "columnWidth": "16",index:index++},
        {"id": "stateLog", "isChecked": "true", "name": "订单状态流转时间", "columnWidth": "30",index:index++},
        {"id": "invoiceInfo", "isChecked": "true", "name": "发票信息", "columnWidth": "30",index:index++},
        {"id": "productId", "isChecked": "true", "name": "商品ID", "columnWidth": "12",index:index++},
        {"id": "realSkuId", "isChecked": "true", "name": "商品编码", "columnWidth": "16",index:index++},
        {"id": "baseRealSkuId", "isChecked": "false", "name": "基准SKU编码", "columnWidth": "20",index:index++},
        {"id": "productName", "isChecked": "true", "name": "商品名称", "columnWidth": "20",index:index++},
        {"id": "amount", "isChecked": "true", "name": "数量", "columnWidth": "8",index:index++},
        {"id": "originalUnitPrice", "isChecked": "true", "name": "商品原价", "columnWidth": "12",index:index++},
        {"id": "unitPrice", "isChecked": "true", "name": "商品单价", "columnWidth": "12",index:index++},
        {"id": "totalPrice", "isChecked": "true", "name": "商品总价", "columnWidth": "12",index:index++},
        {"id": "isPresent", "isChecked": "true", "name": "是否赠品", "columnWidth": "10",index:index++},
        {"id": "createIP", "isChecked": "true", "name": "创建者IP", "columnWidth": "16",index:index++},
        {"id": "productSpec", "isChecked": "true", "name": "商品规格", "columnWidth": "16",index:index++}
    ]
});
print("执行完毕");